apiVersion: v1
kind: ConfigMap
metadata:
  name: newsapp-config
  labels:
    app: newsapp
    release: {{ .Release.Name }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.env.SPRING_PROFILES_ACTIVE }}
  SPRING_RABBITMQ_HOST: {{ .Values.env.SPRING_RABBITMQ_HOST }}
  SPRING_CONFIG_IMPORT: {{ .Values.env.SPRING_CONFIG_IMPORT }}