apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newsapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: "/api"
            pathType: Prefix
            backend:
              service:
                name: newsgroup
                port:
                  number: 8080
