apiVersion: v1
kind: Secret
metadata:
  name: newsapp-secret
type: Opaque
data:
  CONFIGSERVER_URI: {{ .Values.env.CONFIGSERVER_URI | b64enc }}
  SPRING_CONFIG_IMPORT: {{ .Values.env.SPRING_CONFIG_IMPORT | b64enc }}