apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  type: ClusterIP
  selector:
    app: configserver
  ports:
    - protocol: TCP
      port: {{ .Values.configserver.service.port }}
      targetPort: {{ .Values.configserver.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.newsgroup.service.name }}
spec:
  type: ClusterIP
  selector:
    app: newsgroup
  ports:
    - protocol: TCP
      port: {{ .Values.newsgroup.service.port }}
      targetPort: {{ .Values.newsgroup.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: {{ .Values.rabbitmq.service.port }}
      targetPort: {{ .Values.rabbitmq.service.port }}
    - name: management
      protocol: TCP
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: {{ .Values.rabbitmq.service.managementPort }}